runtime: nodejs16

env_variables:
  PORT: 3333
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DOPPLER_TOKEN: 'dp.st.prd_sg_gc.MqfNXQ45taFauNSwfjaTRAEZSDoBggNuSxEk0d9Tiya'

build_env_variables:
  GOOGLE_NODE_RUN_SCRIPTS: ''
