# fly.toml app configuration file generated for ponbook-api on 2023-07-23T14:30:01+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ponbook-api"
primary_region = "sin"

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 75

[env]
  PORT = "3333"
  NODE_ENV = "production"
