name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          key: ponbook-node-modules-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm
        
      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
      
      - name: Deploy application
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
