name: Release
on:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/dev'
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)

    steps:
      - uses: actions/checkout@v3

      - name: create-release-pr
        uses: grassedge/git-pr-release-action@v1.0
        with:
          base: main
          head: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: release
          assign: true
