name: Deploy to Fly.io

on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@v1
        with:
          api_key: ${{ secrets.FLY_API_KEY }}
          app_name: pornbook-api
          config_file: fly.toml
