name: Release

on:
  pull_request:
    types:
      - closed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.base_ref == 'main' && github.head_ref == 'changeset-release/main'
    steps:
      - name: Set git user
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Get tag version
        id: get-tag-version
        run: |
          VERSION=$(cat ./package.json | grep -m 1 version | sed 's/[^0-9.]//g')
          PONBOOK_NEW_TAG=v$VERSION
          echo "PONBOOK_NEW_TAG=$PONBOOK_NEW_TAG" >> $GITHUB_ENV
          echo '::set-output name=newTag::'$PONBOOK_NEW_TAG
          echo '::set-output name=version::'$VERSION
          echo "New release tag is $PONBOOK_NEW_TAG"

      - name: Check should create release
        id: should-create-tag
        run: |
          if [ $(git tag -l "$PONBOOK_NEW_TAG") ]; then
            echo '::set-output name=PONBOOK_TAG_EXISTS::true'
          else
            echo '::set-output name=PONBOOK_TAG_EXISTS::false'
          fi

      - name: Release apps and packages
        if: steps.should-create-tag.outputs.PONBOOK_TAG_EXISTS == 'false'
        uses: changesets/action@v1
        with:
          publish: npx changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
