name: Release
on:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/dev'
    permissions:
      contents: write # to create release (changesets/action)
      pull-requests: write # to create pull request (changesets/action)

    steps:
      - uses: actions/checkout@v3

      - uses: yutailang0119/action-github-pr-release@v3
        with:
          token: ${{ github.token }}
          production-branch: main
          staging-branch: stage
          label: Release
